repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [ --fix ]
        files: ^cli/
      - id: ruff-format
        files: ^cli/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: ^cli/
      - id: end-of-file-fixer
        files: ^cli/
      - id: check-yaml
        files: ^cli/
      - id: check-added-large-files
        files: ^cli/
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        files: ^cli/
